apiVersion: infra.nephio.org/v1alpha1
kind: WorkloadCluster
metadata: # kpt-merge: /workload-cluster
  name: workload-cluster
  annotations:
    config.kubernetes.io/local-config: "true"
    kpt.dev/config-injection: optional
    internal.kpt.dev/upstream-identifier: infra.nephio.org|WorkloadCluster|default|workload-cluster
    kpt.dev/injected-resource: example
spec:
  clusterName: example
  cnis:
  - macvlan
  - ipvlan
  - sriov
  masterInterface: eth0
